### ISSUE TITLE
MacOS Error: Command failed: git config --unset core.editor

### ISSUE THREAD

**Issue by pddd** [lotterfriends/git-flow-buddy#1]
Hi Andre,

Bei 'gfb -p patch' kommt unter MacOS die Fehlermeldung "Error: Command failed: git config --unset core.editor"

> New version: 3.2.7
child_process.js:656
    throw err;
    ^

> Error: Command failed: git config --unset core.editor"
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at /Users/przemyslaw.dul/.npm-global/lib/node_modules/git-flow-buddy/lib/git.js:248:7
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

Grundsätzlich sollte der gfb aber eh nicht den core editor ändern in Zeile 243
https://github.com/lotterfriends/git-flow-buddy/blob/master/lib/git.js 

Weshalb genau änderst du an dieser Stelle den core.editor?
Könnte das Problem mit dem execSync vs exec zusammenhängen?

VG
Przemek

**Comment by lotterfriends** [comment]
Hallo Przemek, 
beim einem merge öffnet sich normalerweise der Standard-Editor und man bestätigt den merge mit dem Speichern des Merge-Files. Ich umgehe dieses verhalten, indem ich den Editor temporär auf stdin setze. Mittlerweile bietet git die  --no-edit Option und man kann die Stelle entsprechend umbauen. https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-merge.html
Ich werde das man asap machen, ansonsten kannst du auch gerne einen Pull-Request erstellen :)

Liebe Grüße, 
André

**Comment by lotterfriends** [comment]
Behoben ab Version 2.2.4

**Comment by pddd** [comment]
Boah, bist du schnell!

Super und lieben vielen Dank!
Przemyslaw Dul
